routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/listSchedules', 'HomeController@listSchedules')->name('list');
    Route::get('/event', function () {
        return view('events/event_data');
    });

    Route::get('/form', function () {
        return view('events/event_form');
    });

    Route::resource('schedules', 'ScheduleController');
    Route::get('/show_share', 'ScheduleController@show_share');
    Route::get('/update_share/{id}/{status}', 'ScheduleController@update_status');
    Route::resource('events', 'EventController');

    Route::get('/profile', 'ProfileController@index');
    // Route::get('/editProfile', 'ProfileController@edit');
    // Route::patch('/editProfile', 'ProfileController@update');
    Route::get('/changePassword', 'ProfileController@editPassword');
    Route::patch('/changePassword', 'ProfileController@updatePassword');
});

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Event extends Model
{
    use Notifiable;

    protected $table = 'events';
    protected $primaryKey = 'id';

    protected $fillable = [
        'name', 'description',
    ];
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Models\Event;
use Illuminate\Http\Request;
use DB;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('events.event_form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = DB::table('events')->insertGetId([
            'name' => $request->name
        ]);

        DB::table('schedules')->insert([
            'event_id' => $id,
            'repeat_id' => $request->repeat,
            'date_start' => $request->date_start
        ]);

        // $events = Event::create($validasi);

        return redirect('/events/create')->with('success', 'Selamat Data berhasil masuk');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function show(Event $event)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function edit(Event $event)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Event $event)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function destroy(Event $event)
    {
        //
    }
}

resources/views/events/event_data.blade.php
@extends('layouts.main')
@extends('layouts.datatable_css')
@extends('layouts.datatable_js')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Kegiatan</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                    <li class="breadcrumb-item active">Jadwal Kegiatan</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
            @if(session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-3">
                            <h3 class="card-title">Jadwal Kegiatan</h3>
                        </div>
                        <div class="col-md-5">
                        </div>
                        <div class="col-md-4 text-right">
                            <a href="{{ url('/show_share') }}"><button type="button" class="btn btn-info"><i
                                        class="fas fa-share-alt"></i> Berbagi</button></a>
                            <a href="{{ route('schedules.create') }}"><button type="button" class="btn btn-primary"><i
                                        class="fas fa-plus"></i> Tambah Kegiatan</button></a>
                        </div>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="example1" class="table table-bordered table-striped text-center">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama Kegiatan</th>
                                <th>Tanggal Mulai</th>
                                <th>Tanggal Selesai</th>
                                <th>Pemilik Kegiatan</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach ($schedules as $schedule)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $schedule->name}}</td>
                                <td>{{ date('d-F-Y', strtotime($schedule->date_start)) }}</td>
                                <td>{{ date('d-F-Y', strtotime($schedule->date_done)) }}</td>
                                <td>{{ $schedule->role }}</td>
                                <td class="d-flex justify-content-around align-items-center">
                                    <a href="{{ route('schedules.show',$schedule->id)}}" class="btn btn-info"
                                        title="Detail"><i class="far fa-eye"></i></a>
                                    @if(Auth::user()->role_id == $schedule->role_id)
                                    <a href="{{ route('schedules.edit',$schedule->id)}}" class="btn btn-warning"
                                        title="Ubah"><i class="far fa-edit"></i></a>
                                    <form action="{{ route('schedules.destroy',$schedule->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger" title="Hapus"><i
                                                class="far fa-trash-alt"></i></button>
                                    </form>
                                    @endif
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
@endsection

resources/views/events/event_detail.blade.php
@extends('layouts.main')
{{-- @extends('layouts.select2_css')
@extends('events.event_setting_js') --}}
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Kegiatan</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
          <li class="breadcrumb-item"><a href="{{ route('schedules.index') }}">Jadwal Kegiatan</a></li>
          <li class="breadcrumb-item active">Detail Kegiatan</li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- general form elements -->
    <div class="card card-default">
      <div class="card-header">
        <h3 class="card-title">Detail Kegiatan</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <div class="card-body">
        <div class="form-group">
          <label for="name_event">Nama Kegiatan</label>
          <h6>{{ $schedules->name }}</h6>
        </div>
        <div class="form-group">
          <label for="tipe_repeat">Jenis</label>
          <h6>{{ $schedules->repeat }}</h6>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-md-6">
              <label for="date_start">Tanggal Mulai</label>
              <h6>{{ $schedules->date_start }}</h6>
            </div>
            <!-- /.col -->
            <div class="col-md-6">
              <label for="date_start">Tanggal Selesai</label>
              <h6>{{ $schedules->date_done }}</h6>
            </div>
            <!-- /.col -->
          </div>
          <!-- /.row -->
        </div>
        <!-- /.form group -->

        <div class="form-group">
          <div class="row">
            <div class="col-md-6">
              <label>Waktu Mulai</label>
              @foreach ($times as $time)
              @if($time->id == $schedules->time_id_start)
              <h6>{{ $time->time }}</h6>
              @break
              @endif
              @endforeach
            </div>
            <!-- /.col -->
            <div class="col-md-6">
              <label>Waktu Selesai</label>
              @foreach ($times as $time)
              @if($time->id == $schedules->time_id_done)
              <h6>{{ $time->time }}</h6>
              @break
              @endif
              @endforeach
            </div>
            <!-- /.col -->
          </div>
          <!-- /.row -->
        </div>
        <!-- /.form group -->
        @if ($schedules->repeat == 'Multi Task')
        <div class="form-group">
          <label>Hari diulang yang dipilih</label>
          <h6>{{ $day }}</h6>
        </div>
        <!-- /.form group -->
        @endif
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div><!-- /.container-fluid -->
</section>

@endsection

resources/views/events/event_form.blade.php
@extends('layouts.main')
@extends('layouts.select2_css')
@extends('events.event_setting_js')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Kegiatan</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
          <li class="breadcrumb-item"><a href="{{ route('schedules.index') }}">Jadwal Kegiatan</a></li>
          <li class="breadcrumb-item active">From Kegiatan</li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- general form elements -->
    <div class="card card-default">
      <div class="card-header">
        <h3 class="card-title">Form Kegiatan</h3>
      </div>
      @if(session()->get('failed'))
      <div class="alert alert-danger"><i class="fa fa-ban"></i>
        {{ session()->get('failed') }}
      </div>
      @endif
      <!-- /.card-header -->
      <!-- form start -->
      @if (empty($type) )
      <form role="form" method="post" action="{{ route('schedules.store')}}">
        @csrf
        @else
        <form role="form" method="post" action="{{ route('schedules.update', $schedules->id) }}">
          @csrf
          @method('PUT')
          @endif
          <div class="card-body">
            <div class="form-group">
              <label for="name_event">Nama Kegiatan</label>
              <input type="text" name="name_id" value="{{ $schedules->event_id }}" hidden>
              @if (empty($type))
              <input type="text" id="name_event" class="form-control @error('name') is-invalid @enderror" name="name"
                placeholder="Masukkan Nama Kegiatan" value="{{ old('name') }}">
              @else
              <input type="text" id="name_event" class="form-control @error('name') is-invalid @enderror" name="name"
                placeholder="Masukkan Nama Kegiatan" value="{{ $schedules->name }}">
              @endif
              @error('name')
              <div class="invalid-feedback">{{ $message }}</div>
              @enderror
            </div>
            <div class="form-group">
              <label for="tipe_repeat">Jenis</label>
              <select class="form-control select2 @error('repeat') is-invalid @enderror" id="tipe_repeat"
                data="{{ $schedules->repeat_id }}" name="repeat" style="width: 100%;">
                @if ($schedules->repeat_id == 2)
                <option value="1" {{ (1 == old('repeat'))?'selected':'' }}>Single Task</option>
                <option selected="selected" value="2" {{ (2 == old('repeat'))?'selected':'' }}>Multi Task</option>
                @else
                <option selected="selected" value="1" {{ (1 == old('repeat'))?'selected':'' }}>Single Task</option>
                <option value="2" {{ (2 == old('repeat'))?'selected':'' }}>Multi Task</option>
                @endif
              </select>
              @error('repeat')
              <div class="invalid-feedback">{{ $message }}</div>
              @enderror
            </div>

            <!-- /.single -->
            <div id="tipe1">
              <div class="form-group">
                <label for="date_start_single">Tanggal</label>
                <div class="input-group">
                  @if (empty($type))
                  <input type="date" name="date_start_single" id="date_start_single"
                    class="form-control float-right @error('date_start_single') is-invalid @enderror"
                    value="{{ old('date_start_single') }}">
                  @else
                  <input type="date" name="date_start_single" id="date_start_single"
                    class="form-control float-right @error('date_start_single') is-invalid @enderror"
                    value="{{ $schedules->date_start }}">
                  @endif
                  @error('date_start_single')
                  <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
                <!-- /.input group -->
              </div>
              <!-- /.form group -->

              <div class="form-group">
                <div class="row">
                  <div class="col-md-6">
                    <label>Waktu Mulai</label>
                    <div class="input-group">
                      <select name="time_start_single"
                        class="select2 form-control @error('time_start_single') is-invalid @enderror">
                        <option value="" disabled>Pilih Waktu...</option>
                        @foreach ($times as $time)
                        <option @if($time->id == $schedules->time_id_start) selected @endif
                          value="{{ $time->id }}"
                          {{ ($time->id == old('time_start_single'))?'selected':'' }}>{{ $time->time }}
                        </option>
                        @endforeach
                      </select>
                      @error('time_start_single')
                      <div class="invalid-feedback">{{ $message }}</div>
                      @enderror
                    </div>
                    <!-- /.input group -->
                  </div>
                  <!-- /.col -->
                  <div class="col-md-6">
                    <label>Waktu Selesai</label>
                    <div class="input-group">
                      <select name="time_done_single"
                        class="select2 form-control @error('time_done_single') is-invalid @enderror">
                        <option value="" disabled>Pilih Waktu...</option>
                        @foreach ($times as $time)
                        <option @if($time->id == $schedules->time_id_done) selected @endif
                          value="{{ $time->id }}"
                          {{ ($time->id == old('time_done_single'))?'selected':'' }}>{{ $time->time }}</option>
                        @endforeach
                      </select>
                      @error('time_done_single')
                      <div class="invalid-feedback">{{ $message }}</div>
                      @enderror
                    </div>
                    <!-- /.input group -->
                  </div>
                  <!-- /.col -->
                </div>
                <!-- /.row -->
              </div>
              <!-- /.form group -->
            </div>
            <!-- /.tipe1 -->

            <!-- /.multi -->
            <div id="tipe2">
              <div class="form-group">
                <div class="row">
                  <div class="col-md-6">
                    <label for="date_start">Tanggal Mulai</label>
                    <div class="input-group">
                      @if (empty($type))
                      <input type="date" id="date_start" name="date_start_multi"
                        class="form-control float-right @error('date_start_multi') is-invalid @enderror"
                        value="{{ old('date_start_multi') }}">
                      @else
                      <input type="date" id="date_start" name="date_start_multi"
                        class="form-control float-right @error('date_start_multi') is-invalid @enderror"
                        value="{{ $schedules->date_start }}">
                      @endif
                      @error('date_start_multi')
                      <div class="invalid-feedback">{{ $message }}</div>
                      @enderror
                    </div>
                    <!-- /.input group -->
                  </div>
                  <!-- /.col -->
                  <div class="col-md-6">
                    <label for="date_done">Tanggal Selesai</label>
                    <div class="input-group">
                      @if (empty($type))
                      <input type="date" id="date_done" name="date_done_multi"
                        class="form-control float-right @error('date_done_multi') is-invalid @enderror"
                        value="{{ old('date_done_multi') }}">
                      @else
                      <input type="date" id="date_done" name="date_done_multi"
                        class="form-control float-right @error('date_done_multi') is-invalid @enderror"
                        value="{{ $schedules->date_done}}">
                      @endif
                      @error('date_done_multi')
                      <div class="invalid-feedback">{{ $message }}</div>
                      @enderror
                    </div>
                    <!-- /.input group -->
                  </div>
                  <!-- /.col -->
                </div>
                <!-- /.row -->
              </div>
              <!-- /.form group -->

              <div class=" form-group">
                <div class="row">
                  <div class="col-md-6">
                    <label for="time_start">Waktu Mulai</label>
                    <div class="input-group">
                      <select name="time_start_multi" id="time_start"
                        class="select2 form-control @error('time_start_multi') is-invalid @enderror">
                        <option value="" disabled>Pilih Waktu...</option>
                        @foreach ($times as $time)
                        <option @if($time->id == $schedules->time_id_start) selected @endif
                          value="{{ $time->id }}"
                          {{ ($time->id == old('time_start_multi'))?'selected':'' }}>{{ $time->time }}</option>
                        @endforeach
                      </select>
                      @error('time_start_multi')
                      <div class="invalid-feedback">{{ $message }}</div>
                      @enderror
                    </div>
                    <!-- /.input group -->
                  </div>
                  <!-- /.col -->
                  <div class="col-md-6">
                    <label for="time_done">Waktu Selesai</label>
                    <div class="input-group">
                      <select name="time_done_multi" id="time_done"
                        class="select2 form-control @error('time_done_multi') is-invalid @enderror">
                        <option value="" disabled>Pilih Waktu...</option>
                        @foreach ($times as $time)
                        <option @if($time->id == $schedules->time_id_done) selected @endif
                          value="{{ $time->id }}"
                          {{ ($time->id == old('time_done_multi'))?'selected':'' }}>{{ $time->time }}</option>
                        @endforeach
                      </select>
                      @error('time_done_multi')
                      <div class="invalid-feedback">{{ $message }}</div>
                      @enderror
                    </div>
                    <!-- /.input group -->
                  </div>
                  <!-- /.col -->
                </div>
                <!-- /.row -->
              </div>
              <!-- /.form group -->

              <div class="form-group">
                <label for="day_repeat">Hari yang diulang</label>
                <div class="d-flex">
                    <div class="form-check mr-3 icheck-primary d-inline">
                        <input type="checkbox" id="every_day" value=""/>
                        <label for="every_day">Semua Hari</label>
                    </div>
                    <?php $i = 0 ?>
                    @foreach ($days as $day)
                        <div class="form-check mr-3 icheck-primary d-inline">
                            <input @if(isset($repeat_days[$i]) && ($repeat_days[$i]->day_id == $day->id)) {{ $i++ }} checked
                            @endif
                            name="repeat_day[]" type="checkbox"
                            id="{{ $day->day }}" value="{{ $day->id }}">
                            <label for="{{ $day->day }}">{{ $day->day }}
                            </label>
                        </div>
                    @endforeach
                </div>
                <!-- /.d-flex -->
                @error('repeat_day')
                <div style="font-size: 80%; color: #dc3545;">{{ $message }}</div>
                @enderror
              </div>
              <!-- /.form group -->

            </div>
            <!-- /.tipe2 -->
          </div>
          <!-- /.card-body -->
          <div class="card-footer float-right">
            <button type="submit" class="btn btn-success px-4">Submit</button>
          </div>
        </form>
    </div>
    <!-- /.card -->
  </div><!-- /.container-fluid -->
</section>

@endsection

resources/views/events/event_setting_js.blade.php
@extends('layouts.select2_js')
@section('add_js')
<script>
    $(document).ready(function(){

    var type = $("#tipe_repeat"). val();
    if(type == '2'){
        $("#tipe1").hide();
        $("#tipe2").show();
    }else if(type == '1'){
        $("#tipe2").hide();
        $("#tipe1").show();
    }
    // Untuk mengganti tampilan saat select option jenis kegiatan terganti
    // Pada Tampilan event_form.blade.php
    $('#tipe_repeat').on('change', function(){
        var divisiId = $(this). children("option:selected"). val();

        if(divisiId == '2'){
            $("#tipe1").hide();
            $("#tipe2").show();
        }
        else if(divisiId == '1'){
            $("#tipe2").hide();
            $("#tipe1").show();
        }
    });

    // menceklis seluruh hari
    $('#every_day').click(function() {
        $('input:checkbox').not(this).prop('checked', this.checked);
    });
});
</script>
@endsection

resources/views/events/event_share.blade.php
@extends('layouts.main')
@extends('layouts.datatable_css')
@extends('layouts.datatable_js')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Kegiatan</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                    <li class="breadcrumb-item">Jadwal Kegiatan</li>
                    <li class="breadcrumb-item active">Berbagi Kegiatan</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">

            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-3">
                            <h3 class="card-title">Berbagi Kegiatan</h3>
                        </div>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="example1" class="table table-bordered table-striped text-center">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama</th>
                                <th>Status</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach ($shares as $share)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $share->role}}</td>
                                <td>{{ $share->status }}</td>
                                <td>
                                    <a href="{{ url('/update_share/'.$share->id.'/'.$share->status)}}"
                                        class="btn btn-warning" title="Ubah"><i class="far fa-edit"></i></a>
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
@endsection